package com;
class ExceptionExample {
public void show() {
String a = "i am error";
System.out.println(a);
try {
int i = 50/0;//Arithmetic Exception occurs /0
System.out.println(i);
String s = "Jeet";
System.out.println(s.length());
int arr[] = new int [3];
arr[14] = 24;//Array Index out of bound Exception
int m = Integer.parseInt(s);//Parses the string argument as decimal integer
System.out.println(m);
}
catch(Exception e)//It catches the first exception 
{
System.out.println(e);
}
String b = "i cannot be handled";
System.out.println(a +  b);
}
public static void main(String[] args) {
ExceptionExample ep = new ExceptionExample();//Creating the object of the above class
ep.show();//calling the method
}
}
